FROM python:3.11-slim

WORKDIR /app

# Copy requirements và install dependencies 
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt 

# Copy source code
COPY src/ ./src
COPY tests/ ./tests/

# Set Python path
ENV PYTHONPATH=/app

# Run Consumer 
CMD ["python", "src/kafka_consumer/run_consumer.py"]
